### ISSUE TITLE
Support dash 3.0.0

### ISSUE THREAD

**Issue by nhoover** [jimmybow/visdcc#54]
In the recent major update to dash, they have changed things a bit for components: https://github.com/plotly/dash/releases/tag/v3.0.0

Here's the error when attempting to import with dash 3.0.0:

File "D:\GitHub\xxx\modules\app.py", line 5, in
import visdcc
File "D:\GitHub\venvs\python3.13\Lib\site-packages\visdcc_init_.py", line 8, in
_components = _dash.development.component_loader.load_components(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'dash.development' has no attribute 'component_loader'

**Comment by jimmybow** [comment]
OK,  I migrate to v0.0.60 for dash 3.0.0,
but some feature may need test.

**Comment by nhoover** [comment]
Thanks very much for the quick update! I am just using Run_js but it is working fine with dash 3.0.0.
